_archive/ASP.NET Core Demo/WebApplication.Knockout/Controllers/HomeController.cs
using System;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using DotNetify.Routing;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace WebApplication.Core.Controllers
{
   public class HomeController : Controller
   {
      private readonly IHostingEnvironment _hostingEnvironment;

      public HomeController(IHostingEnvironment hostingEnvironment)
      {
         _hostingEnvironment = hostingEnvironment;
      }

      public IActionResult Index(string id) => Demo("index");

      [Route("Demo/{*id}")]
      public IActionResult Demo(string id)
      {
         if (String.IsNullOrEmpty(id))
            id = "index";

         if (id.EndsWith("_cshtml"))
            return View("/Views/" + id.Replace("_cshtml", ".cshtml"));

         // If not ending with .js or .map, assume it's a request for static html file.
         if (!id.EndsWith(".js") && !id.EndsWith(".map"))
            id = Path.Combine(_hostingEnvironment.ContentRootPath, "Views/" + (id.EndsWith(".html") ? id : id + ".html"));
         return File(id);
      }

      [Route("WebStore/{*id}")]
      public IActionResult WebStore(string id)
      {
         var initialRoutingData = new RoutingViewData("/webstore/" + id, "WebStore/Index_cshtml", typeof(ViewModels.WebStore.NavBarVM));
         return ViewComponent("Routing", new { iViewData = initialRoutingData });
      }

      private FileStreamResult File(string path)
      {
         var mimeType = "text/plain";
         if (path.EndsWith(".js", StringComparison.OrdinalIgnoreCase))
            mimeType = "text/js";
         else if (path.EndsWith(".html", StringComparison.OrdinalIgnoreCase))
            mimeType = "text/html";
         return File(System.IO.File.OpenRead(path), mimeType);
      }
   }

   /// <summary>
   /// View component to build content for server-side routing.
   /// </summary>
   public class RoutingViewComponent : ViewComponent
   {
      private readonly IHostingEnvironment _hostingEnvironment;

      public RoutingViewComponent(IHostingEnvironment hostingEnvironment)
      {
         _hostingEnvironment = hostingEnvironment;
      }

      public IViewComponentResult Invoke(RoutingViewData iViewData)
      {
         IRoutable model;
         var viewId = RoutableExtension.Route(ref iViewData, out model);
         if (viewId != null)
         {
            ViewData["Routing"] = iViewData;
            var id = viewId.Replace("/Demo/", "");
            if (id.EndsWith("_cshtml"))
               return View("/Views/" + id.Replace("_cshtml", ".cshtml"), model?.GetType() != typeof(object) ? model : null);

            var htmlFilePath = Path.Combine(_hostingEnvironment.ContentRootPath, "Views/" + (id.EndsWith(".html") ? id : id + ".html"));
            return new HtmlResult(htmlFilePath);
         }
         return null;
      }
   }

   /// <summary>
   /// View component result that returns HTML content given its file path.
   /// </summary>
   public class HtmlResult : IViewComponentResult
   {
      private string _html;

      public HtmlResult(string htmlFilePath)
      {
         var fileStream = File.OpenRead(htmlFilePath);
         using (StreamReader reader = new StreamReader(fileStream))
         {
            _html = reader.ReadToEnd();
         }
      }

      public void Execute(ViewComponentContext context) => context.Writer.Write(_html);
      public Task ExecuteAsync(ViewComponentContext context) => context.Writer.WriteAsync(_html);
   }
}

_archive/ASP.NET Core Demo/WebApplication.Knockout/Views/WebStore/BookCategory.cshtml
@using DotNetify.Routing
@model ViewModels.WebStore.BookCategoryVM

<div data-vm="BookCategoryVM" @Html.Raw(Model != null ? Model.InitArgs(ViewData["Routing"]) : null)>
   <div class="page-header">
      <h2 data-bind="text: CategoryName">@(Model != null ? Model.CategoryName : "")</h2>
   </div>
   <div>
      @if (Model != null)
      {
         <div class="row">
            @for(int i = 0; i < Model.Books.Count; i++ )
            {
               var book = Model.Books[i];
               <div class="book col-md-3" data-bind="with: Books()[@i]">
                  <center>
                     <a data-bind="vmRoute: Route"><img class="thumbnail" src="@book.ImageUrl" /></a>
                     <strong>@book.Title</strong>
                     <div>by <span>@book.Author</span></div>
                     <br />
                  </center>
               </div>
            }
         </div>
      }
      else
      {
         <div class="row" data-bind="foreach: Books">
            <div class="book col-md-3">
               <center>
                  <a data-bind="vmRoute: Route"><img class="thumbnail" data-bind="attr: {src: ImageUrl}" /></a>
                  <strong data-bind="text: Title"></strong>
                  <div>by <span data-bind="text: Author"></span></div>
                  <br />
               </center>
            </div>
         </div>
      }
      <br />
   </div>
</div>

_archive/ASP.NET Core Demo/WebApplication.Knockout/Views/WebStore/BookDetails.cshtml
@using DotNetify.Routing
@model ViewModels.WebStore.BookDetailsVM

<div data-vm="BookDetailsVM" @Html.Raw(Model != null ? Model.InitArgs(ViewData["Routing"]) : null)>
   <br />
   <div class="page-header">
      <div>
         <div class="row">
            <div class="col-md-3 book">
               <img class="thumbnail" data-bind="attr: {src: ImageUrl}" src="@(Model != null ? Model.ImageUrl : "")" />
            </div>
            <div class="col-md-7">
               <div class="product-overview">
                  <h2 data-bind="text: Title">@(Model != null ? Model.Title : "")</h2>
                  <h4>
                     by <span data-bind="text: Author">@(Model != null ? Model.Author : "")</span>
                  </h4>
                  <div>
                     <br />
                     <a data-bind="attr: {href: ItemUrl}">
                        <button type="button" class="btn btn-lg btn-primary">Buy</button>
                     </a>
                  </div>
                  <div>
                     <br />
                     <!-- Nav tabs -->
                     <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active" data-bind="css: {active: ShowDetails}"><a href="#DetailsTab" role="tab" data-toggle="tab">Details</a></li>
                        <li role="presentation" data-bind="css: {active: ShowReviews}"><a href="#ReviewsTab" role="tab" data-toggle="tab">Reviews</a></li>
                     </ul>

                     <!-- Tab panes -->
                     <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" data-bind="css: {active: ShowDetails}" id="DetailsTab">
                           <div class="well">
                              <div><b>ISBN:</b> 1234567890</div>
                              <div><b>Publisher:</b> ACME Publishing</div>
                              <div><b>Format:</b> Paperback</div>
                           </div>
                        </div>
                        <div role="tabpanel" class="tab-pane" data-bind="css: {active: ShowReviews}" id="ReviewsTab">
                           <div class="well">
                              <div>
                                 <b>The ACME Times Book Review</b>
                              </div>
                              Another strong offering from best-seller author <span data-bind="text: Author"></span>... This book elevates the genre.
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

_archive/ASP.NET Core Demo/WebApplication.Knockout/Views/WebStore/BookStore.cshtml
@using DotNetify.Routing
@model IRoutable

<div data-vm="BookStoreVM" @Html.Raw(Model != null ? Model.InitArgs(ViewData["Routing"]) : null)>
   <div id="BookStoreCategory">
      <br />
      <div class="panel panel-success">
         <div class="panel-heading">
            <h3 class="panel-title">Select a category</h3>
         </div>
         <div class="panel-body">
            <ul class="nav nav-sidebar" data-bind="foreach: Categories">
               <li data-bind="css: { active: $root.$router.isActive(Route) }"><a href="" data-bind="text: Name, vmRoute: Route"></a></li>
            </ul>
         </div>
      </div>
   </div>
</div>

<div id="BookStorePanel" class="container-fluid">
   <div class="row">
      <div class="col-md-9">
         <div id="BookStoreContent">
            @if (Model != null) { @await Component.InvokeAsync("Routing", new { iViewData = ViewData["Routing"] }) }
         </div>
      </div>
   </div>
</div>

_archive/ASP.NET Core Demo/WebApplication.Knockout/Views/WebStore/Index.cshtml
@using DotNetify.Routing
@model IRoutable

<!DOCTYPE html>
<html>
<head>
   <title></title>
   <meta charset="utf-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link href="/css/demo/bootstrap.min.css" rel="stylesheet">
   <link href="/css/demo/webstore.css" rel="stylesheet">
   <script src="/lib/require.min.js" data-main="/js/demo/demoApp"></script>
</head>
<body>
   <div class="container-fluid">
      <div class="header clearfix">
         <h3>Example: Web Store</h3>
      </div>
      <!-- Fixed navbar -->
      <div class="container-fluid" data-vm="NavBarVM" @Html.Raw(Model.InitArgs(ViewData["Routing"]))>
         <nav class="navbar navbar-default">
            <div class="navbar-header">
               <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand"><b>ACME</b></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
               <ul class="nav navbar-nav" data-bind="foreach: MenuItems">
                  <li data-bind="css: { active: $root.$router.isActive(Route) }"><a data-bind="text: Caption, vmRoute: Route"></a></li>
               </ul>
            </div><!--/.nav-collapse -->
         </nav>
      </div>
      <div id="NavContent" class="container-fluid">
         @if (Model != null)
         { @await Component.InvokeAsync("Routing", new { iViewData = ViewData["Routing"] }) }
      </div> <!-- /container -->
   </div>
</body>
</html>